Repository daleal/zum, pull requests merged in 2021-03, with the labels that each got.

#2 Re-architect zum
  .pylintrc
  zum/abstractions.py
  zum/cli.py
  zum/configs/__init__.py
  zum/configs/core.py
  zum/configs/errors.py
  zum/constants.py
  zum/core.py
  zum/engine.py
  zum/errors.py
  zum/executor.py
  zum/parser.py
  zum/requests/__init__.py
  zum/requests/core.py
  zum/requests/errors.py
  zum/requests/models.py
  zum/requests/validations.py
  zum/utils.py
  zum/validations.py
Labels: chore, design, refactor

#3 Add documentation
  Makefile
  README.md
  pyproject.toml
Labels: documentation

#4 Prepare 0.0.2 release
  pyproject.toml
  zum/__init__.py
Labels: release

#5 Release version 0.0.2
  .pylintrc
  Makefile
  README.md
  pyproject.toml
  tests/test_core.py
  zum/__init__.py
  zum/abstractions.py
  zum/cli.py
  zum/configs/__init__.py
  zum/configs/core.py
  zum/configs/errors.py
  zum/constants.py
  zum/engine.py
  zum/errors.py
  zum/executor.py
  zum/parser.py
  zum/requests/__init__.py
  zum/requests/core.py
  zum/requests/errors.py
  zum/requests/models.py
  zum/requests/validations.py
  zum/utils.py
  zum/validations.py
Labels: release

#11 Fix `--version` command
  zum/cli.py
  zum/engine.py
Labels: bugfix

#12 Add a test battery
  .coveragerc
  tests/configs/__init__.py
  tests/configs/test_core.py
  tests/requests/__init__.py
  tests/requests/test_core.py
  tests/requests/test_models.py
  tests/requests/test_valdiations.py
  tests/test_engine.py
  zum/configs/core.py
Labels: chore, tests

#13 Minor documentation upgrades
  README.md
Labels: documentation

#14 Prepare 0.0.3 release
  pyproject.toml
  zum/__init__.py
Labels: version bump

#15 Release version 0.0.3
  .coveragerc
  README.md
  pyproject.toml
  tests/configs/__init__.py
  tests/configs/test_core.py
  tests/requests/__init__.py
  tests/requests/test_core.py
  tests/requests/test_models.py
  tests/requests/test_valdiations.py
  tests/test_engine.py
  zum/__init__.py
  zum/cli.py
  zum/configs/core.py
  zum/engine.py
Labels: release

#16 Fix endpoint validation
  zum/configs/core.py
Labels: bugfix

#17 Prepare 0.0.4 release
  pyproject.toml
  zum/__init__.py
Labels: version bump

#18 Release version 0.0.4
  pyproject.toml
  zum/__init__.py
  zum/configs/core.py
Labels: release

#19 Add type support to the body parameters
  tests/requests/test_core.py
  tests/requests/test_helpers.py
  tests/requests/test_valdiations.py
  zum/constants.py
  zum/requests/core.py
  zum/requests/errors.py
  zum/requests/helpers.py
  zum/requests/validations.py
Labels: feature

#20 Document body parameter casting
  README.md
Labels: documentation

#21 Prepare 0.1.0 release
  pyproject.toml
  zum/__init__.py
Labels: version bump

#22 Release version 0.1.0
  README.md
  pyproject.toml
  tests/requests/test_core.py
  tests/requests/test_helpers.py
  tests/requests/test_valdiations.py
  zum/__init__.py
  zum/constants.py
  zum/requests/core.py
  zum/requests/errors.py
  zum/requests/helpers.py
  zum/requests/validations.py
Labels: release

#23 Support headers
  tests/conftest.py
  tests/requests/test_core.py
  tests/requests/test_models.py
  tests/test_executor.py
  zum/executor.py
  zum/requests/core.py
  zum/requests/models.py
Labels: feature

#24 Document header support
  README.md
Labels: documentation

#25 Prepare 0.2.0 release
  pyproject.toml
  zum/__init__.py
Labels: version bump

#26 Release version 0.2.0
  README.md
  pyproject.toml
  tests/conftest.py
  tests/requests/test_core.py
  tests/requests/test_models.py
  tests/test_executor.py
  zum/__init__.py
  zum/executor.py
  zum/requests/core.py
  zum/requests/models.py
Labels: release

#27 Add tests
  tests/conftest.py
  tests/test_cli.py
  tests/test_engine.py
  tests/test_executor.py
  zum/cli.py
  zum/engine.py
Labels: tests

#28 Minor changes
  .github/PULL_REQUEST_TEMPLATE/release.md
  Makefile
  README.md
  pyproject.toml
Labels: chore

#29 Update documentation examples
  README.md
  tests/configs/test_core.py
  tests/requests/test_core.py
  tests/requests/test_helpers.py
  tests/requests/test_models.py
Labels: chore, documentation

#33 Change color badge color
  README.md
Labels: bugfix, documentation

#35 Update tagline and descriptions
  README.md
  pyproject.toml
Labels: documentation

#36 Update readme with documentation
  README.md
  pyproject.toml
Labels: chore, documentation

#37 Prepare 0.2.1 release
  pyproject.toml
  zum/__init__.py
Labels: version bump

#38 Release version 0.2.1
  .github/PULL_REQUEST_TEMPLATE/release.md
  Makefile
  README.md
  pyproject.toml
  tests/configs/test_core.py
  tests/conftest.py
  tests/requests/test_core.py
  tests/requests/test_helpers.py
  tests/requests/test_models.py
  tests/test_cli.py
  tests/test_engine.py
  tests/test_executor.py
  zum/__init__.py
  zum/cli.py
  zum/engine.py
Labels: release

#40 Fix a README inline code block
  README.md
Labels: documentation

#41 Add CLI param for config file
  pyproject.toml
  tests/cli/__init__.py
  tests/cli/test_core.py
  tests/cli/test_generators.py
  tests/cli/test_utils.py
  tests/test_cli.py
  tests/test_utils.py
  zum/cli.py
  zum/cli/__init__.py
  zum/cli/core.py
  zum/cli/generators.py
  zum/cli/utils.py
  zum/constants.py
  zum/engine.py
  zum/utils.py
Labels: feature

#42 Documentation changes
  .github/CONTRIBUTING.md
  README.md
Labels: documentation
